### ISSUE TITLE
Change how-to-gopro to GoPro SOP and fix style

### ISSUE THREAD

**Issue by hsx1** [MPI-tSCN/Templates#12]
For the [how-to-gopro](https://github.com/MPI-tSCN/experiment-scheduler/issues/documentation/src/how-tos/HowTo_GoProHero10.md) file, please fix the following aspects:

- [ ]  move file to src > sop > light-measurement-devices > goprohero10.md
- [ ]  fix numbering in markdown style (here is a [quick overview](https://carpentries-incubator.github.io/markdown-intro/06-lists/index.html))

cc @niloufartabandeh

**Comment by GittyMPI** [comment]
Hi you two! I changed the file according to Hannahs suggestions in the SOP (Thanks for your feedback, by the way 👍). It´s now stored in a new path and the numbering is also adapted. I´m not 100% sure if it is correct so let me know if there´s anything else.
